;;; -*- lexical-binding: t -*-
(require 'init-startup)
(require 'init-basic)
(require 'init-package)
(require 'init-projectile)
(require 'init-ui)
(require 'init-winum)
;; (require 'init-auto-save)

(require 'init-which-key)
(require 'init-embark)

(require 'init-crux)
(require 'init-ivy)
(require 'init-undo-tree)
(require 'init-discover-my-major)
(require 'init-ibuffer)
;; (require 'init-recentf)
;; (require 'init-treemacs)
(require 'init-eaf)
;; (require 'init-meow)
(require 'init-coding)
;; (require 'init-org)
;; (require 'init-magit)
;; (require 'init-smartparens)
;; ------------
(provide 'init)
